name: test_project

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 2.0.9
  flutter_bloc: 8.1.3
  dio: 5.3.3
  json_annotation: 4.8.1
  another_flushbar: 1.12.30

  cupertino_icons: 1.0.2

dev_dependencies:
  build_runner: 2.4.6
  json_serializable: 6.7.1

  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
